name: test-build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          git config --global user.name "github"
          git config --global user.email "github@users.noreply.github.com"
      - name: Test
        run: npm run test
      - name: create release
        id: createrelease
        uses: gregoranders/nodejs-create-release@v0.0.18
        with:
          tag: 1.0.0.
          name: node - 1.0.0 Release
          target: ${{ github.ref }}
